### ISSUE TITLE
Plugin can't read spigot.yml when using Thermos (Spigot/Forge server)

### ISSUE THREAD

**Issue by fucnknown** [possi/MineVive#3]
**Server Log: http://pastebin.com/2bDUxJuD

It seems people can only teleport to blocks that you would be able to walk to as a normal player. All other teleports iether give you a "moved to quickly" or "moved to quick".

When you install it via spigot it writes the configs you need to change into the spigot.yml file.

This is how the config is supposed to look when written by spigot.

http://pastebin.com/9F331XuB

This is how it looks written by Thermos

http://pastebin.com/1uhVAFM7

And if the settings are written by hand, it seem to not read the edits.

moved-wrongly-threshold: moved-too-quickly-threshold:

Could you make it so the plugin can read the configuration by itself? Or check why it's not working?

Mods installed.

appliedenergistics2-rv2-stable-10.jar
buildcraft-7.1.16.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
denseores-1.6.2.jar
ironchest-1.7.10-6.0.60.741-universal.jar
Jabba-1.1.4_1.7.10.jar
magicalcrops-1.7.10_0.1.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
Pam's HarvestCraft 1.7.10Lb.jar
StorageDrawers-1.7.10-1.9.8.jar
worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar

Plugins Installed:
MineVive.jar
ProtocolLib.jar

Thermos Version:
Thermos-1.7.10-1614-server.jar v57, v55, v54 : https://github.com/CyberdyneCC/Thermos/releases

**Comment by possi** [comment]
spigot.yml is for server setting. It is not task of the MineVive plugin to change the limitation. The Purpose of the Plugin is only to tell the Minecraft-Client: "This Server is aware of teleportation, go ahead and try it". Otherwise it would default back to non-teleportation without trying.

> No way around this. Once again: Use Spigot, or modify minecraft yourself. There is no chance a Spigot/Bukkit-Plugin can solve this.
